language: generic 
sudo: required
services:
  - docker
  
  
before_install:
  - docker build -t joshgrafton/docker-react -f Dockerfile.dev .
  
  script:
    - docker run -e CI=true joshgrafton/docker-react npm run test -- --coverage